### ISSUE TITLE
google.golang.org/appengine/delay doesn't work in Go1.11 anymore?

### ISSUE THREAD

**Issue by yegle** [golang/appengine#166]
Calling `delay.Func.Call()` returns `nil` and I don't see the task en-queued on Cloud Task dashboard (and no more request to `/_ah/queue/go/delay`.

**Comment by mtraver** [comment]
It seems to work. The app below behaves as expected.

Can you confirm you're using the latest `google.golang.org/appengine` package?

app.yaml
```yaml
runtime: go111

handlers:
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  secure: always
```

go.mod
```go
module mymod

require google.golang.org/appengine v1.2.0
```

main.go
```go
package main

import (
	"context"
	"fmt"
	"io"
	"net/http"

	"google.golang.org/appengine"
	"google.golang.org/appengine/delay"
	gaelog "google.golang.org/appengine/log"
)

var laterFunc = delay.Func("myfunc", func(ctx context.Context, s string) {
	gaelog.Infof(ctx, "Hello from task queue! Here's a message: %v", s)
})

func rootHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}

	ctx := appengine.NewContext(r)

	w.Header().Set("Content-Type", "text/plain")

	if err := laterFunc.Call(ctx, "hi"); err != nil {
		io.WriteString(w, fmt.Sprintf("Func call failed: %v", err))
	} else {
		io.WriteString(w, "Func call succeeded")
	}
}

func main() {
	http.HandleFunc("/", rootHandler)

	appengine.Main()
}
```
